### ISSUE TITLE
Inference on a video

### ISSUE THREAD

**Issue by claussteinmassl** [princeton-computational-imaging/NSF#1]
Looking forward to the code release. Your work sounds very interesting! 

I‘m wondering if it could be adapted to be used with videos / image sequences instead of burst images (given they have enough parallax) so the transmission and occlusion are calculated for each frame of the sequence. 
Extracting or recreating transmission and occlusion is a tedious manual task in traditionell compositing. This could be a game changer for this kind of tasks. Example use cases are screen inserts, label changes of products, removal of signs etc. 

I assume temporal consistency could be an issue. Also thinking about moving occlusions (e.g. a person is moving and seen in the reflection / occlusion). 

Thanks in advance!
Cheers,
Claus

**Comment by Ilya-Muromets** [comment]
Great question. I plan to release code to process regular images (e.g., a stack of .PNGs) in addition to the RAW burst data I use for the project, however the project itself is mostly focused on burst-photography. So, I cannot guarantee (nor expect) great performance on generic videos, and leave that to follow-up work.

In my experience it is unfortunately very difficult to make something like this work for both small and large camera motion. In the case of small motion you can assume that everything in the scene can be divided into a couple (mostly flat) layers, but as motion gets larger (e.g., you're filming a skateboarding doing tricks in a skate park) you now have to worry about how you're going to represent complex 3D geometry (e.g., you can't see the bottom of the skateboard in the first frame, but you can see it in the 45th frame, how do you store/generate that part of the scene).

**Comment by Ilya-Muromets** [comment]
Code now released, feel free to open up the issue again if you have any more questions!
