### ISSUE TITLE
Updates on the code release?

### ISSUE THREAD

**Issue by bmanga** [princeton-computational-imaging/NSF#2]
Hi,

I'd be interested in having a look at the code... Is there an updated timeframe for its release?

Thanks :)

**Comment by Ilya-Muromets** [comment]
Almost done! Just wrapping up some README stuff and should publish in the next couple days

**Comment by bmanga** [comment]
thanks for the update :) Looking forward to it!

**Comment by Ilya-Muromets** [comment]
Done! Took a little while since I wanted to add a Google Colab tutorial, but now should hopefully be a lot easier to get start with the code.
