### ISSUE TITLE
How to test directly on custom dataset without training the model on them?

### ISSUE THREAD

**Issue by mohiiieldin** [princeton-computational-imaging/NSF#7]
Is there a way to test directly on custom images? also if I want to test on a single image should I repeat it to mimic the burst images or is it okay?

Thanks.

**Comment by Ilya-Muromets** [comment]
This work uses motion to separate layers (e.g. a reflection moving less than the objects behind it), so unfortunately it will not work for single image obstruction removal. Happy to discuss more in the other thread.

**Comment by mohiiieldin** [comment]
Thanks for the clarification.
